using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UPSAPIv2.Models.Columns
{
    internal class Shipments
    {
        public static List<string> ShipToFrom = new List<string> {
             "Name",
             "AttentionName",
             "Phone",
             "FaxNumber",
             "Address1",
             "Address2",
             "Address3",
             "City",
             "State",
            "Zip" };
        public static List<string> LabelParameters = new List<string> {
            "LabelSpecification",
            "LabelParametersDescription",
            "LabelCharacterSet",
            "LabelWidth",
            "LabelHeight",
            "LabelInstructionCode",
            "LabelImageFormatCode" };
        public static List<string> ShipmentCharge = new List<string> {
            "Type",
            "AccountNumber",
            "AlternatePaymentMethod",
            "BillShipper",
            "BillThirdParty",
            "BillReceiver",
            "BillReceiverAddress1",
            "BillReceiverAddress2",
            "BillReceiverAddress3",
            "BillThirdPartyAddress1",
            "BillThirdPartyAddress1",
            "BillThirdPartyAddress1",
            "CertifiedElectronicMail",
            "ConsigneeBilledIndicator",
            "CreditCard",
            "CreditCardBillingAddress",
            "CreditCardSecurityCode",
            "CreditCardType",
            "InterchangeSystemCode" };
        public static List<string> Package = new List<string>() {
            "NumHazMatPackages",
            "Description",
            "PalletDescription",
            "NumOfPieces",
            "UnitPrice",
            "PackagingType",
            "PackagingDescription",
            "UnitOfLengthMeasurement",
            "UnitOfMeasurementDescription",
            "DimensionsLength",
            "DimensionsWidth",
            "DimensionsHeight",
            "UnitOfWeightMeasurement",
            "DimWeight",
            "PackageWeightUnitOfMeasurement",
            "PackageWeight",
            "LargePackageIndicator",
            "OversizeIndicator",
            "MinimumBillableWeightIndicator",
            "AdditionalHandlingIndicator",
            "ReferenceNumber",
            "BarCodeIndicator",
            "SimpleRate",
            "UPSPremier",
            "UPSPremierSensorID",
            "UPSPremierHandlingInstructions",
            "PackageServiceOptions",
            "DeliveryConfirmation",
            "DCISType",
            "DCISNumber",
            "DeclaredValue",
            "DeclaredValueCode",
            "DeclaredValuePrice",
            "COD",
            "CODFundsCode",
            "CODCurrencyCode",
            "CODPrice",
            "AccessPointCOD",
            "AccessPointCODCode",
            "AccessPointCODPrice",
            "ShipperReleaseIndicator",
            "Notification",
            "NotificationCode",
            "EmailSubjectCode",
            "EmailAddress",
            "EmailSubject",
            "FromEMailAddress",
            "FromEMailName",
            "UndeliverableEMailAddress",
            "EMailMemo",
            "HazMat",
            "HazMatQty",
            "HazMatID1",
            "HazMatID2",
            "HazMatID3",
            "HazMatSubRiskClass",
            "HazMataDRItemNumber",
            "HazMatPackingGroup",
            "HazMatTechnicalName",
            "HazMatHazardLabelRequired",
            "HazMatClassDivisionNumber",
            "HazMatReferenceNumber",
            "HazMatQuantity",
            "UOM",
            "HazMatPackagingType",
            "IDNumber",
            "HazMatProperShippingName",
            "HazMatAdditionalDescription",
            "HazMatEmergencyPhone",
            "HazMatEmergencyContact",
            "HazMatReportableQuantity",
            "HazMatRegulationSet",
            "HazMatTransportationMode",
            "HazMatCommodityRegulatedLevelCode",
            "HazMatTransportCategory",
            "HazMatTunnelRestrictionCode",
            "ChemicalRecordIdentifier",
            "LocalTechnicalName",
            "LocalProperShippingName",
            "DryIce",
            "DryIceRegulationSet",
            "DryIceUnitOfWeightMeasurement",
            "DryIceWeight",
            "DryIceMedicalUseIndicator",
            "UPSPremiumCareIndicator",
            "ProactiveIndicator",
            "PackageIdentifier",
            "ClinicalTrialsID",
            "RefrigerationIndicator",
            "Commodity",
            "PrimeCode",
            "FreightClass",
            "NMFCSubCode",
            "NMFCSubCode",
            "HazMatPackageInformation",
            "HazMatAllPackedInOneIndicator",
            "HazMatOverPackedIndicator",
            "HazMatQValue",
            "HazMatOuterPackagingType" };
    }
}
